apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: second-app
      tier: backend     
  template:
    metadata:
      labels:
        name: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: soniharshil54/kub-first-app:2
        
            